// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorWithCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorWithCodeRequest) Reset()         { *m = ErrorWithCodeRequest{} }
func (m *ErrorWithCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ErrorWithCodeRequest) ProtoMessage()    {}
func (*ErrorWithCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_212ba36637511684, []int{0}
}
func (m *ErrorWithCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorWithCodeRequest.Unmarshal(m, b)
}
func (m *ErrorWithCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorWithCodeRequest.Marshal(b, m, deterministic)
}
func (dst *ErrorWithCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorWithCodeRequest.Merge(dst, src)
}
func (m *ErrorWithCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ErrorWithCodeRequest.Size(m)
}
func (m *ErrorWithCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorWithCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorWithCodeRequest proto.InternalMessageInfo

func (m *ErrorWithCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type WrapErrorWithCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Wraps                int64    `protobuf:"varint,2,opt,name=wraps,proto3" json:"wraps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapErrorWithCodeRequest) Reset()         { *m = WrapErrorWithCodeRequest{} }
func (m *WrapErrorWithCodeRequest) String() string { return proto.CompactTextString(m) }
func (*WrapErrorWithCodeRequest) ProtoMessage()    {}
func (*WrapErrorWithCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_212ba36637511684, []int{1}
}
func (m *WrapErrorWithCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapErrorWithCodeRequest.Unmarshal(m, b)
}
func (m *WrapErrorWithCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapErrorWithCodeRequest.Marshal(b, m, deterministic)
}
func (dst *WrapErrorWithCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapErrorWithCodeRequest.Merge(dst, src)
}
func (m *WrapErrorWithCodeRequest) XXX_Size() int {
	return xxx_messageInfo_WrapErrorWithCodeRequest.Size(m)
}
func (m *WrapErrorWithCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapErrorWithCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WrapErrorWithCodeRequest proto.InternalMessageInfo

func (m *WrapErrorWithCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WrapErrorWithCodeRequest) GetWraps() int64 {
	if m != nil {
		return m.Wraps
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_212ba36637511684, []int{2}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ErrorWithCodeRequest)(nil), "testpb.ErrorWithCodeRequest")
	proto.RegisterType((*WrapErrorWithCodeRequest)(nil), "testpb.WrapErrorWithCodeRequest")
	proto.RegisterType((*Empty)(nil), "testpb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	ErrorWithCode(ctx context.Context, in *ErrorWithCodeRequest, opts ...grpc.CallOption) (*Empty, error)
	WrapErrorWithCode(ctx context.Context, in *WrapErrorWithCodeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) ErrorWithCode(ctx context.Context, in *ErrorWithCodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/testpb.Test/ErrorWithCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) WrapErrorWithCode(ctx context.Context, in *WrapErrorWithCodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/testpb.Test/WrapErrorWithCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	ErrorWithCode(context.Context, *ErrorWithCodeRequest) (*Empty, error)
	WrapErrorWithCode(context.Context, *WrapErrorWithCodeRequest) (*Empty, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_ErrorWithCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorWithCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).ErrorWithCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testpb.Test/ErrorWithCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).ErrorWithCode(ctx, req.(*ErrorWithCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_WrapErrorWithCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrapErrorWithCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).WrapErrorWithCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testpb.Test/WrapErrorWithCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).WrapErrorWithCode(ctx, req.(*WrapErrorWithCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testpb.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ErrorWithCode",
			Handler:    _Test_ErrorWithCode_Handler,
		},
		{
			MethodName: "WrapErrorWithCode",
			Handler:    _Test_WrapErrorWithCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_212ba36637511684) }

var fileDescriptor_test_212ba36637511684 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0x94, 0xb4, 0xb8, 0x44,
	0x5c, 0x8b, 0x8a, 0xf2, 0x8b, 0xc2, 0x33, 0x4b, 0x32, 0x9c, 0xf3, 0x53, 0x52, 0x83, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x17, 0x2e, 0x89, 0xf0, 0xa2, 0xc4, 0x02, 0x62, 0xd5, 0x0b,
	0x89, 0x70, 0xb1, 0x96, 0x17, 0x25, 0x16, 0x14, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0x41,
	0x38, 0x4a, 0xec, 0x5c, 0xac, 0xae, 0xb9, 0x05, 0x25, 0x95, 0x46, 0x7d, 0x8c, 0x5c, 0x2c, 0x21,
	0x20, 0xbd, 0x76, 0x5c, 0xbc, 0x28, 0x66, 0x0a, 0xc9, 0xe8, 0x41, 0x5c, 0xa7, 0x87, 0xcd, 0x2a,
	0x29, 0x5e, 0xb8, 0x2c, 0xc8, 0x18, 0x25, 0x06, 0x21, 0x37, 0x2e, 0x41, 0x0c, 0x77, 0x09, 0x29,
	0xc0, 0x54, 0xe1, 0x72, 0x32, 0x86, 0x39, 0x49, 0x6c, 0xe0, 0xa0, 0x31, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x39, 0x20, 0xef, 0xbd, 0x28, 0x01, 0x00, 0x00,
}
