image: golang:latest

stages:
  - test

vet:
  stage: test
  script:
    - make vet

check_fmt:
  stage: test
  script:
    - make checkfmt

unit_test:
  parallel:
    matrix:
      - GO: ["1.21", "1.22"]
  image:
    name: golang:$GO
  stage: test
  script:
    - make test
