// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.2
// source: jettison.proto

package jettisonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jettison_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_jettison_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_jettison_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WrappedError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Binary       string          `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	StackTrace   []string        `protobuf:"bytes,6,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Code         string          `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	Source       string          `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	KeyValues    []*KeyValue     `protobuf:"bytes,8,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty"`
	JoinedErrors []*WrappedError `protobuf:"bytes,3,rep,name=joined_errors,json=joinedErrors,proto3" json:"joined_errors,omitempty"`
	WrappedError *WrappedError   `protobuf:"bytes,4,opt,name=wrapped_error,json=wrappedError,proto3" json:"wrapped_error,omitempty"`
}

func (x *WrappedError) Reset() {
	*x = WrappedError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jettison_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WrappedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedError) ProtoMessage() {}

func (x *WrappedError) ProtoReflect() protoreflect.Message {
	mi := &file_jettison_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedError.ProtoReflect.Descriptor instead.
func (*WrappedError) Descriptor() ([]byte, []int) {
	return file_jettison_proto_rawDescGZIP(), []int{1}
}

func (x *WrappedError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WrappedError) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *WrappedError) GetStackTrace() []string {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

func (x *WrappedError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WrappedError) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WrappedError) GetKeyValues() []*KeyValue {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

func (x *WrappedError) GetJoinedErrors() []*WrappedError {
	if x != nil {
		return x.JoinedErrors
	}
	return nil
}

func (x *WrappedError) GetWrappedError() *WrappedError {
	if x != nil {
		return x.WrappedError
	}
	return nil
}

var File_jettison_proto protoreflect.FileDescriptor

var file_jettison_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6a, 0x65, 0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6a, 0x65, 0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x22, 0x32, 0x0a, 0x08,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0xc6, 0x02, 0x0a, 0x0c, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6a, 0x65, 0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a,
	0x65, 0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x65,
	0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x0c, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e, 0x2f,
	0x6a, 0x65, 0x74, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_jettison_proto_rawDescOnce sync.Once
	file_jettison_proto_rawDescData = file_jettison_proto_rawDesc
)

func file_jettison_proto_rawDescGZIP() []byte {
	file_jettison_proto_rawDescOnce.Do(func() {
		file_jettison_proto_rawDescData = protoimpl.X.CompressGZIP(file_jettison_proto_rawDescData)
	})
	return file_jettison_proto_rawDescData
}

var file_jettison_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jettison_proto_goTypes = []interface{}{
	(*KeyValue)(nil),     // 0: jettisonpb.KeyValue
	(*WrappedError)(nil), // 1: jettisonpb.WrappedError
}
var file_jettison_proto_depIdxs = []int32{
	0, // 0: jettisonpb.WrappedError.key_values:type_name -> jettisonpb.KeyValue
	1, // 1: jettisonpb.WrappedError.joined_errors:type_name -> jettisonpb.WrappedError
	1, // 2: jettisonpb.WrappedError.wrapped_error:type_name -> jettisonpb.WrappedError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jettison_proto_init() }
func file_jettison_proto_init() {
	if File_jettison_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jettison_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jettison_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WrappedError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jettison_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jettison_proto_goTypes,
		DependencyIndexes: file_jettison_proto_depIdxs,
		MessageInfos:      file_jettison_proto_msgTypes,
	}.Build()
	File_jettison_proto = out.File
	file_jettison_proto_rawDesc = nil
	file_jettison_proto_goTypes = nil
	file_jettison_proto_depIdxs = nil
}
