// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jettison.proto

package jettisonpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hop struct {
	Binary               string   `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	StackTrace           []string `protobuf:"bytes,3,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hop) Reset()         { *m = Hop{} }
func (m *Hop) String() string { return proto.CompactTextString(m) }
func (*Hop) ProtoMessage()    {}
func (*Hop) Descriptor() ([]byte, []int) {
	return fileDescriptor_jettison_e7a7a6a8fc361e35, []int{0}
}
func (m *Hop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hop.Unmarshal(m, b)
}
func (m *Hop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hop.Marshal(b, m, deterministic)
}
func (dst *Hop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hop.Merge(dst, src)
}
func (m *Hop) XXX_Size() int {
	return xxx_messageInfo_Hop.Size(m)
}
func (m *Hop) XXX_DiscardUnknown() {
	xxx_messageInfo_Hop.DiscardUnknown(m)
}

var xxx_messageInfo_Hop proto.InternalMessageInfo

func (m *Hop) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Hop) GetStackTrace() []string {
	if m != nil {
		return m.StackTrace
	}
	return nil
}

func (m *Hop) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 string      `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Source               string      `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Parameters           []*KeyValue `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_jettison_e7a7a6a8fc361e35, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Error) GetParameters() []*KeyValue {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_jettison_e7a7a6a8fc361e35, []int{2}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Hop)(nil), "jettisonpb.Hop")
	proto.RegisterType((*Error)(nil), "jettisonpb.Error")
	proto.RegisterType((*KeyValue)(nil), "jettisonpb.KeyValue")
}

func init() { proto.RegisterFile("jettison.proto", fileDescriptor_jettison_e7a7a6a8fc361e35) }

var fileDescriptor_jettison_e7a7a6a8fc361e35 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x66, 0xb7, 0xba, 0x53, 0x10, 0x1d, 0x16, 0xc9, 0xcd, 0xd2, 0x53, 0xbd, 0xf4,
	0x50, 0xfd, 0x0b, 0x82, 0xe0, 0xad, 0x88, 0x57, 0x49, 0xe3, 0x20, 0x75, 0xdd, 0x4d, 0x98, 0x64,
	0x85, 0x3d, 0xfb, 0xc7, 0x25, 0x69, 0x82, 0xbd, 0xcd, 0xf7, 0xe6, 0x91, 0xf7, 0x32, 0x70, 0xf5,
	0x45, 0xde, 0x4f, 0xce, 0x1c, 0x3b, 0xcb, 0xc6, 0x1b, 0x84, 0xcc, 0x76, 0x6c, 0x26, 0x10, 0xcf,
	0xc6, 0xe2, 0x2d, 0x94, 0xe3, 0x74, 0x54, 0x7c, 0x96, 0x45, 0x5d, 0xb4, 0xdb, 0x21, 0x11, 0xde,
	0x41, 0xe5, 0xbc, 0xd2, 0xfb, 0x77, 0xcf, 0x4a, 0x93, 0x14, 0xb5, 0x68, 0xb7, 0x03, 0x44, 0xe9,
	0x35, 0x28, 0x78, 0x0f, 0x25, 0x31, 0x1b, 0x76, 0x72, 0x55, 0x8b, 0xb6, 0xea, 0x6f, 0xba, 0xff,
	0xc7, 0xbb, 0xa7, 0xb0, 0x19, 0x92, 0xa1, 0xf9, 0x2d, 0x60, 0x13, 0x15, 0x44, 0x58, 0x6b, 0xf3,
	0x41, 0x72, 0x1d, 0xb3, 0xe2, 0x8c, 0x12, 0x2e, 0x0e, 0xe4, 0x9c, 0xfa, 0xa4, 0x54, 0x21, 0x63,
	0xe8, 0xe6, 0xcc, 0x89, 0x35, 0xc9, 0xd5, 0xdc, 0x6d, 0x26, 0x7c, 0x04, 0xb0, 0x8a, 0xd5, 0x81,
	0x3c, 0xb1, 0x8b, 0xd5, 0xaa, 0x7e, 0xb7, 0x8c, 0x7f, 0xa1, 0xf3, 0x9b, 0xfa, 0x3e, 0xd1, 0xb0,
	0xf0, 0x35, 0x3d, 0x5c, 0x66, 0x1d, 0xaf, 0x41, 0xec, 0x29, 0x7f, 0x39, 0x8c, 0xb8, 0x83, 0xcd,
	0x4f, 0x58, 0xa5, 0xa8, 0x19, 0xc6, 0x32, 0xde, 0xed, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x85,
	0xb0, 0x0a, 0xf9, 0x49, 0x01, 0x00, 0x00,
}
